Repository GSG-G7/shrinc, pull requests merged in 2019-11, with the labels that each got.

#90 get profile data
  client/.gitignore
  client/src/components/App/index.js
  client/src/components/common/AvailabilityTime/index.js
  client/src/components/common/Location/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Profile/style.css
Labels: Done

#82 results page
  client/src/components/App/index.js
  client/src/components/common/Button/index.js
  client/src/components/common/Card/cardContent.js
  client/src/components/common/Card/index.js
  client/src/components/common/Card/style.css
  client/src/components/pages/Results/index.js
  client/src/components/pages/Results/style.css
  client/src/components/pages/index.js
  package-lock.json
  server/router/index.js
Labels: Done

#95 questionnaire page and progress Bar
  client/src/components/App/index.js
  client/src/components/common/Questionary/Question.js
  client/src/components/common/Questionary/index.js
  client/src/components/common/Questionary/qustionsStatic.js
  client/src/components/common/Questionary/renderSteps.js
  client/src/components/common/Questionary/style.css
  client/src/components/pages/QuestionaryPage/index.js
  client/src/components/pages/QuestionaryPage/style.css
  client/src/utils/index.js
  client/src/utils/rateHighestTypeTherapy.js
  client/src/utils/ratesForAllQuestions.js
Labels: Done

#102 add title to all pages
  client/package-lock.json
  client/package.json
  client/src/components/App/index.js
  client/src/components/pages/About/index.js
  client/src/components/pages/Glossary/index.js
  client/src/components/pages/NotFound/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Results/index.js
  client/src/components/pages/Signup/index.js
  client/src/components/pages/TherapyType/index.js
Labels: Done

#103 Favicon
  client/public/index.html
  client/public/logo.ico
  server/app.js
Labels: Done

#112 edit questionnaire route
  client/src/components/App/index.js
  client/src/components/common/Header/menuData.js
Labels: Done

#113 create simple loader component
  client/src/components/common/Loader/index.js
  client/src/components/common/Loader/style.css
Labels: Done

#116 profile company insurance
  client/src/components/pages/Profile/index.js
Labels: Done

#115 Fix menu bug
  client/src/components/common/Header/index.js
Labels: Done

#118 add Loader component to pages that need loading
  client/src/components/common/Loader/style.css
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Results/index.js
Labels: Done

#125 create cities route
  server/controllers/index.js
  server/controllers/routes/cities.js
  server/controllers/routes/index.js
  server/router/index.js
Labels: Done

#127 Edit insurance input
  client/src/components/pages/Signup/index.js
  client/src/components/pages/Signup/staticData.js
Labels: Done

#126 make pages responsive
  client/src/components/common/Header/index.js
  client/src/components/pages/About/style.css
  client/src/components/pages/Signup/index.js
  client/src/components/pages/Signup/style.css
  client/src/components/pages/TherapyType/style.css
Labels: Done

#124 Map component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/common/Location/index.js
  client/src/components/common/Location/style.css
  client/src/components/common/Questionary/index.js
  client/src/components/pages/Signup/index.js
Labels: Awaiting Review

#79 initial Filter page
  client/src/components/App/index.js
  client/src/components/common/Card/index.js
  client/src/components/common/Filter/index.js
  client/src/components/common/Filter/staticData.js
  client/src/components/common/Filter/style.css
  client/src/components/common/index.js
  client/src/components/pages/FilterPage/index.js
  client/src/components/pages/FilterPage/style.css
  client/src/components/pages/index.js
Labels: Awaiting Review

#136 fix menu in desktop screen
  client/src/components/common/Header/style.css
Labels: Awaiting Review

#97 Filter Result Component
  client/src/components/common/FilterResult/index.js
  client/src/components/common/FilterResult/staticData.js
  client/src/components/common/FilterResult/style.css
  client/src/components/common/Questionary/index.js
  client/src/components/common/Questionary/renderSteps.js
  client/src/components/common/index.js
  client/src/components/pages/Results/index.js
Labels: Done

#139 React lazy
  client/src/components/App/index.js
  client/src/components/App/style.css
  client/src/components/common/Loader/index.js
  client/src/components/pages/index.js
Labels: Done

#129 Responsive and Style
  client/src/components/common/AvailabilityTime/style.css
  client/src/components/common/Card/cardContent.js
  client/src/components/common/Card/style.css
  client/src/components/common/Filter/index.js
  client/src/components/common/Header/style.css
  client/src/components/common/Location/style.css
  client/src/components/common/availabilityTable/style.css
  client/src/components/pages/FilterPage/style.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/Home/style.css
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Profile/style.css
Labels: Awaiting Review

#141 Edit insurance in signup
  client/src/components/pages/Signup/index.js
Labels: Done

#137 refactor questionnaire
  client/src/components/common/Questionary/Question.js
  client/src/components/common/Questionary/index.js
  client/src/components/common/Questionary/renderSteps.js
  client/src/components/pages/QuestionaryPage/style.css
  client/src/components/pages/Results/index.js
Labels: Done

#148 change tagline in homepage
  client/src/components/pages/Home/index.js
  client/src/components/pages/Home/style.css
Labels: Awaiting Review, Done

#143 on submit signup
  client/src/components/common/index.js
  client/src/components/pages/Signup/index.js
  client/src/components/pages/Signup/style.css
  server/controllers/routes/signup.js
  server/controllers/validation/signupValidation.js
Labels: Done

#152 update glossary data and style
  client/src/components/pages/Glossary/glossaryData.json
  client/src/components/pages/Glossary/index.js
  client/src/components/pages/Glossary/style.css
Labels: Awaiting Review

#153 remove semicolon from Questionnaire page
  client/src/components/pages/QuestionaryPage/index.js
Labels: Done

#155 Edit confirm password in signup
  client/src/components/pages/Signup/index.js
Labels: Done

#156 change the route from types to questionnaire
  client/src/components/pages/Home/index.js
Labels: Done

#157 Edit validation in signup page
  client/src/components/pages/Signup/index.js
Labels: Done

#158 149 fix filter component
  client/src/components/App/index.js
  client/src/components/common/Card/cardContent.js
  client/src/components/common/Card/index.js
  client/src/components/common/Filter/index.js
  client/src/components/common/Filter/staticData.js
  client/src/components/pages/FilterPage/index.js
  client/src/components/pages/Signup/index.js
Labels: Done

#159 149 fix filter component
  client/src/components/App/index.js
  client/src/components/common/Button/index.js
  client/src/components/common/Header/menuData.js
  client/src/components/common/Questionary/index.js
Labels: Done

#170 change names for menu items
  client/src/components/common/Header/menuData.js
  client/src/components/common/Header/style.css
Labels: Done

#172 edit link position
  client/src/components/pages/Home/style.css
Labels: Done

#175 change statments in search page as required
  client/src/components/common/Filter/index.js
  client/src/components/pages/FilterPage/index.js
Labels: Done

#177 change the main description in Front Page
  client/src/components/pages/Home/index.js
  client/src/components/pages/Home/style.css
Labels: Done

#191 add I to Integrative word
  client/src/components/common/FilterResult/staticData.js
Labels: Awaiting Review

#192 user testing changes
  client/src/components/pages/Glossary/glossaryData.json
  client/src/components/pages/Home/index.js
Labels: Done

#203 add therapy types to static data
  client/src/components/pages/TherapyType/staticData.js
Labels: Done

#196 General Look in style
  client/src/components/common/Card/style.css
  client/src/components/common/Filter/style.css
  client/src/components/pages/About/style.css
  client/src/components/pages/FilterPage/index.js
  client/src/components/pages/FilterPage/style.css
  client/src/components/pages/Glossary/index.js
  client/src/components/pages/Glossary/style.css
  client/src/components/pages/Home/style.css
  client/src/components/pages/QuestionaryPage/index.js
  client/src/components/pages/QuestionaryPage/style.css
  client/src/components/pages/TherapyType/style.css
Labels: Done

#197 search bar in glossary
  client/src/components/pages/Glossary/index.js
  client/src/components/pages/Glossary/style.css
Labels: Awaiting Review

#198 sort Items in the result points
  client/src/components/common/FilterResult/index.js
  client/src/components/common/FilterResult/style.css
Labels: Done

#195 Refactoring profile page
  client/src/components/common/AvailabilityTime/style.css
  client/src/components/common/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Profile/staticData.js
  client/src/components/pages/Profile/style.css
Labels: Done

#204 Bug in profile end point
  server/controllers/routes/profile.js
Labels: Done

#189 Edit validation & spelling mistakes
  client/src/components/common/Filter/index.js
  client/src/components/common/Filter/style.css
  client/src/components/common/Location/index.js
  client/src/components/common/Location/style.css
  client/src/components/pages/Signup/index.js
  client/src/components/pages/Signup/staticData.js
  server/controllers/routes/signup.js
  server/controllers/validation/signupValidation.js
Labels: Done

#206 refactor ReadMe file
  README.md
Labels: Done

#193 refactor Questionnaire page
  client/src/components/common/FilterResult/index.js
  client/src/components/common/Questionary/Question.js
  client/src/components/common/Questionary/index.js
  client/src/components/common/Questionary/style.css
  client/src/components/common/Questionnaire/MultiChoicesQuestion.js
  client/src/components/common/Questionnaire/SingleChoiceQuestion.js
  client/src/components/common/Questionnaire/index.js
  client/src/components/common/Questionnaire/qustionsStatic.js
  client/src/components/common/index.js
  client/src/components/pages/QuestionaryPage/index.js
  client/src/components/pages/QuestionaryPage/style.css
  client/src/components/pages/Results/index.js
  client/src/utils/rateHighestTypeTherapy.js
Labels: Awaiting Review

#207 fix display launch app locally
  README.md
Labels: Done

#209 edit style in questionary
  client/src/components/common/Questionnaire/index.js
  client/src/components/pages/QuestionaryPage/style.css
Labels: Done

#211 simple changes in signup
  client/src/components/pages/Signup/index.js
Labels: Done

#210 do some changes | Prioritized changes
  client/src/components/pages/About/index.js
  client/src/components/pages/Home/index.js
Labels: Done

#212 change Find the right therapy for you + Search for therapsits
  client/src/components/common/Header/menuData.js
Labels: Done

#215 Minor changes to spelling and punctuation
  client/src/components/common/FilterResult/index.js
  client/src/components/common/Header/menuData.js
  client/src/components/common/Questionnaire/index.js
  client/src/components/common/Questionnaire/qustionsStatic.js
  client/src/components/pages/About/index.js
  client/src/components/pages/Home/index.js
  client/src/components/pages/QuestionaryPage/index.js
  client/src/components/pages/Results/index.js
  client/src/components/pages/Signup/index.js
  client/src/components/pages/TherapyType/staticData.js
Labels: Awaiting Review
